# Generated by Django 3.2 on 2022-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='media/image/profile'),
        ),
    ]
