# Generated by Django 3.2 on 2022-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_birthday',
            field=models.BooleanField(default=False),
        ),
    ]
