# Generated by Django 3.2 on 2022-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220712_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
