# Generated by Django 3.2 on 2022-08-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Auther',
            new_name='auther',
        ),
    ]
