# Generated by Django 3.2 on 2022-08-01 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_rename_message_messagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Message',
        ),
    ]
