# Generated by Django 3.2 on 2022-08-02 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_rename_messagemodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room',
            field=models.ManyToManyField(related_name='room', to=settings.AUTH_USER_MODEL),
        ),
    ]
