# Generated by Django 3.2 on 2022-08-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.chatroom'),
        ),
    ]
